
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [11, 8]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./botfilter b
            - uses: actions/upload-artifact@v2
              with:
                name: BotFilter
                path: BotFilter-proxy/proxy/build/libs/*-all.jar